### ISSUE TITLE
Cannot build 32bit packages

### ISSUE THREAD

**Issue by bmwiedemann** [openSUSE/slowroll#1]
Most notably the `Mesa-32bit` package is available in Tumbleweed, but we cannot build it in the Slowroll update repos, because with the [download-on-demand mechanism](https://build.opensuse.org/projects/openSUSE:Tumbleweed/meta), we currently only have access to the snapshot of what was published for Tumbleweed.

Adrian proposed to have a 2nd repo publish with the missing packages.

I would prefer to use `osc release` to get the matching sources along with the binaries, but Adrian thinks that is too expensive an operation to take all 15000 Factory packages. Maybe we could identify a subset of what is needed
* to build -32bit packages
* to build java packages
* to build an installer DVD iso with `product-builder` (needs around 4000 binary packages)
* maybe also have an own repo that works with the NET-install iso
My guesstimate is that 3000 source packages could suffice.

**Comment by dirkmueller** [comment]
afaik only a subset is built for 32bit, everything else is in LegacyX86. why can we not release the necessary packages alongside the tumbleweed release?

I think a 32bit product flavor would be needed?

**Comment by bmwiedemann** [comment]
CC @DimStar77 

Apart from 32bit packages, we also want an own DVD installer iso for easy openQA testing and user-install. That needs a different solution.

**Comment by DimStar77** [comment]
IMHO, the fact that slowroll builds against a released TW snapshot is a problem in itself. This can only lead to ABI weirdness (think updated glibc in TW - slowroll has basically no chance to not jump if it builds against TW)

Building against TW should only be used for bootstrap purposes (in which case you probably better build against /standard) and then completely be decoupled to be an own distro

TW does not publish any i586 packages - we only publish the -32bit.x86_64 (which, granted, are technically repackaged i586 packages; but for RPM they are x86_64 packages) - One way out of this misery was the option to create an extra FTP tree for i586 (not published under the standard TW tree)

**Comment by bmwiedemann** [comment]
> One way out of this misery was the option to create an extra FTP tree for i586

Yes. Can you please do that?

**Comment by bmwiedemann** [comment]
Publishing a Tumbleweed i586 tree turned out hard, because of some missing packages.
I solved i586 and java builds with some added source-level packages in openSUSE:Slowroll, openSUSE:Slowroll:Base and openSUSE:Slowroll:Staging.
Even NET isos build now, but DVDs don't yet.

**Comment by bmwiedemann** [comment]
DVDs also build for some months. This syncs binaries from Factory to the :Base repo before the version bump with https://github.com/openSUSE/slowroll-tools/blob/prod/tools/obsrsync
